### ISSUE TITLE
Use temporary directory

### ISSUE THREAD

**Issue by fwenzel** [meermanr/MakeMKV-installer#1]
Funny to see this script in your repository -- did we have the same idea at roughly the same time?

https://gist.github.com/3375705
http://fredericiana.com/2012/08/16/a-small-script-to-install-or-update-makemkv-on-linux/

Anyhow, I use a temporary directory for all the build cruft rather than dumping it all into `cwd` so I suggest you do the same.

**Comment by meermanr** [comment]
As always, you have a valid point! :)

**Comment by meermanr** [comment]
Actually on second thought, I don't see how you can get old versions from the official site, so I prefer to keep the old copies around...

But thanks for taking the time to point this out!

**Comment by meermanr** [comment]
FWIW, it turns out they _do_ keep all their versions online, but they don't seem to list them any where. For instance:

```
http://www.makemkv.com/download/makemkv-bin-1.8.0.tar.gz
http://www.makemkv.com/download/makemkv-bin-1.7.1.tar.gz
```
